export const questions = [
  // ========== PHẦN 1: 9 CÂU HỎI VỀ CHỈ SỐ Y TẾ (BẮT BUỘC) ==========
  {
    id: 'gender',
    text: 'Giới tính của bạn?',
    type: 'select',
    placeholder: 'Chọn giới tính',
    options: [
      { value: 'male', label: 'Nam' },
      { value: 'female', label: 'Nữ' },
      { value: 'other', label: 'Khác' },
    ],
    hint: 'Thông tin giới tính giúp đánh giá chính xác hơn',
  },
  {
    id: 'age',
    text: 'Tuổi của bạn?',
    type: 'number',
    placeholder: 'Nhập tuổi (VD: 25)',
    min: 0,
    max: 120,
    unit: 'tuổi',
    hint: 'Tuổi hiện tại của bạn',
  },
  {
    id: 'pregnancies',
    text: 'Số lần mang thai?',
    type: 'number',
    placeholder: 'Nhập số lần (VD: 0, 1, 2...)',
    min: 0,
    max: 20,
    unit: 'lần',
    hint: 'Dành cho nữ. Nếu là nam hoặc chưa từng mang thai thì nhập 0',
  },
  {
    id: 'glucose',
    text: 'Nồng độ Glucose (đường huyết lúc đói)?',
    type: 'number',
    placeholder: 'Nhập nồng độ glucose (VD: 95)',
    min: 0,
    max: 300,
    unit: 'mg/dL',
    hint: 'Bình thường: 70-100 mg/dL',
    tooltip: {
      title: '🩸 Cách đo Glucose',
      items: [
        '• 🏥 Tại bệnh viện/phòng khám: Xét nghiệm máu',
        '• 📱 Tại nhà: Máy đo đường huyết',
        '• 💡 Sản phẩm gợi ý: Accu-Chek, OneTouch, FreeStyle',
        '• ⏰ Đo vào buổi sáng sau 8-12h nhịn ăn',
        '',
        '📊 Chỉ số tham khảo:',
        '  ✅ Bình thường: 70-99 mg/dL',
        '  ⚠️ Tiền tiểu đường: 100-125 mg/dL',
        '  🔴 Tiểu đường: ≥126 mg/dL',
      ],
    },
  },
  {
    id: 'bloodPressure',
    text: 'Huyết áp tâm trương (chỉ số dưới)?',
    type: 'number',
    placeholder: 'Nhập huyết áp (VD: 80)',
    min: 0,
    max: 200,
    unit: 'mmHg',
    hint: 'Bình thường: 60-80 mmHg',
    tooltip: {
      title: '💓 Cách đo Huyết áp',
      items: [
        '• 🏥 Tại phòng khám: Máy đo chuyên nghiệp',
        '• 🏠 Tại nhà: Máy đo huyết áp điện tử',
        '• 💡 Sản phẩm gợi ý: Omron, Beurer, Microlife',
        '• ⏰ Đo khi nghỉ ngơi, không vận động mạnh',
        '',
        '📊 Ví dụ: Huyết áp 120/80 mmHg',
        '  → Lấy số 80 (chỉ số dưới)',
        '',
        '  ✅ Bình thường: <80 mmHg',
        '  ⚠️ Cao: ≥80 mmHg',
      ],
    },
  },
  {
    id: 'skinThickness',
    text: 'Độ dày nếp gấp da (tùy chọn)?',
    type: 'number',
    placeholder: 'Nhập độ dày (VD: 20) hoặc 0',
    min: 0,
    max: 100,
    unit: 'mm',
    hint: 'Trung bình: 15-30 mm. Nhập 0 nếu không biết',
    tooltip: {
      title: '📏 Cách đo độ dày da',
      items: [
        '• 🏥 Tại phòng khám: Thước kẹp đo da (Caliper)',
        '• 📱 Tại nhà: Thước kẹp mỡ cơ thể',
        '• 💡 Sản phẩm: Accu-Measure Body Fat Caliper',
        '• 📍 Vị trí: Sau cánh tay (giữa vai và khuỷu)',
        '• 👉 Nhúm da lên, đo bằng thước kẹp',
        '',
        '⚠️ Nếu không có thiết bị:',
        '  Nhập 0 - hệ thống sẽ tự ước tính',
      ],
    },
  },
  {
    id: 'insulin',
    text: 'Nồng độ Insulin (tùy chọn)?',
    type: 'number',
    placeholder: 'Nhập nồng độ (VD: 80) hoặc 0',
    min: 0,
    max: 900,
    unit: 'µU/mL',
    hint: 'Bình thường lúc đói: 2-25 µU/mL. Nhập 0 nếu chưa xét nghiệm',
    tooltip: {
      title: '🔬 Cách đo Insulin',
      items: [
        '• 🏥 Xét nghiệm tại bệnh viện/phòng khám',
        '• 📋 Tên: "Insulin huyết thanh"',
        '• ⏰ Thường đo sau ăn 2 giờ',
        '• 💰 Chi phí: 150,000-300,000 VNĐ',
        '',
        '📊 Bình thường lúc đói: 2-25 µU/mL',
        '',
        '⚠️ Nếu chưa xét nghiệm:',
        '  Nhập 0 - hệ thống sẽ tự ước tính',
      ],
    },
  },
  {
    id: 'bmi',
    text: 'Chỉ số BMI (Body Mass Index)?',
    type: 'number',
    placeholder: 'Nhập BMI (VD: 23.5)',
    min: 0,
    max: 70,
    unit: 'kg/m²',
    step: 0.1,
    hint: 'BMI = Cân nặng(kg) / Chiều cao²(m²). Bình thường: 18.5-24.9',
    tooltip: {
      title: '🧮 Cách tính BMI',
      items: [
        '📏 Công thức:',
        '  BMI = Cân nặng (kg) / [Chiều cao (m)]²',
        '',
        '📝 Ví dụ: Cao 1.7m, nặng 70kg',
        '  BMI = 70 / (1.7 × 1.7) = 24.2',
        '',
        '💻 Công cụ tính online:',
        '  • calculator.net/bmi-calculator.html',
        '  • bmi-calculator.vn',
        '',
        '📱 App: MyFitnessPal, BMI Calculator',
        '',
        '📊 Chỉ số tham khảo:',
        '  ✅ Bình thường: 18.5-24.9',
        '  ⚠️ Thừa cân: 25-29.9',
        '  🔴 Béo phì: ≥30',
      ],
    },
  },
  {
    id: 'diabetesPedigreeFunction',
    text: 'Tiền sử gia đình về tiểu đường?',
    type: 'number',
    placeholder: 'Nhập giá trị (VD: 0.5)',
    min: 0,
    max: 3,
    step: 0.1,
    hint: 'Chỉ số nguy cơ di truyền (0-3). Càng cao càng nguy hiểm.',
    tooltip: {
      title: '🧬 Cách ước tính nguy cơ di truyền',
      items: [
        '📋 Dựa vào tiền sử gia đình:',
        '',
        '0.2 - Không ai bị tiểu đường',
        '0.4 - Ông bà, cô dì, chú bác bị',
        '0.6 - Anh chị em bị',
        '0.8 - Một trong bố/mẹ bị',
        '1.0 - Cả bố và mẹ bị',
        '1.5+ - Nhiều người trong gia đình bị',
        '',
        '💡 Nếu không chắc chắn:',
        '  • Không có: 0.2-0.3',
        '  • Ít người: 0.4-0.6',
        '  • Nhiều người: 0.7-1.0',
      ],
    },
  },
  
  // ========== PHẦN 2: 12 CÂU HỎI VỀ TRIỆU CHỨNG TIỂU ĐƯỜNG ==========
  {
    id: 'symptom_thirsty',
    text: 'Bạn có thường xuyên cảm thấy khát nước bất thường không?',
    type: 'select',
    placeholder: 'Chọn mức độ',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng' },
      { value: 2, label: 'Thường xuyên' },
      { value: 3, label: 'Rất thường xuyên' },
    ],
    hint: 'Khát nước nhiều là triệu chứng điển hình của tiểu đường',
    tooltip: {
      title: '💧 Khát nước bất thường',
      items: [
        '📋 Dấu hiệu cảnh báo:',
        '• Uống nhiều nước hơn bình thường',
        '• Luôn cảm thấy khô miệng',
        '• Uống nước nhưng vẫn khát',
        '• Thức dậy ban đêm vì khát nước',
        '',
        '⚠️ Nguyên nhân:',
        'Đường huyết cao làm cơ thể mất nước',
        '',
        '💡 Chọn đáp án phù hợp:',
        '• Không: Bình thường',
        '• Thỉnh thoảng: 1-2 lần/tuần',
        '• Thường xuyên: Hầu như mỗi ngày',
        '• Rất thường xuyên: Suốt ngày',
      ],
    },
  },
  {
    id: 'symptom_urination',
    text: 'Bạn có đi tiểu nhiều hơn bình thường không?',
    type: 'select',
    placeholder: 'Chọn mức độ',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng' },
      { value: 2, label: 'Thường xuyên (>8 lần/ngày)' },
      { value: 3, label: 'Rất nhiều (>10 lần/ngày, cả đêm)' },
    ],
    hint: 'Đi tiểu nhiều lần, đặc biệt ban đêm',
    tooltip: {
      title: '🚽 Tiểu nhiều (Polyuria)',
      items: [
        '📋 Dấu hiệu:',
        '• Đi tiểu >8 lần trong ngày',
        '• Thức dậy 2-3 lần/đêm để đi vệ sinh',
        '• Lượng nước tiểu nhiều mỗi lần',
        '',
        '⚠️ Tại sao?',
        'Thận phải lọc và thải bỏ đường dư thừa',
        '',
        '📊 Bình thường: 6-8 lần/ngày',
      ],
    },
  },
  {
    id: 'symptom_hunger',
    text: 'Bạn có cảm thấy đói thường xuyên mặc dù đã ăn đủ?',
    type: 'select',
    placeholder: 'Chọn mức độ',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng' },
      { value: 2, label: 'Thường xuyên' },
      { value: 3, label: 'Luôn luôn đói' },
    ],
    hint: 'Đói bất thường ngay cả sau khi ăn',
    tooltip: {
      title: '🍽️ Đói liên tục (Polyphagia)',
      items: [
        '📋 Biểu hiện:',
        '• Đói ngay sau khi ăn xong',
        '• Ăn nhiều nhưng vẫn đói',
        '• Thèm ăn liên tục',
        '',
        '⚠️ Nguyên nhân:',
        'Tế bào không nhận được glucose',
        'Cơ thể tưởng đang thiếu năng lượng',
      ],
    },
  },
  {
    id: 'symptom_fatigue',
    text: 'Bạn có thường xuyên cảm thấy mệt mỏi, uể oải?',
    type: 'select',
    placeholder: 'Chọn mức độ',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng mệt' },
      { value: 2, label: 'Mệt thường xuyên' },
      { value: 3, label: 'Luôn kiệt sức' },
    ],
    hint: 'Mệt mỏi kéo dài dù nghỉ ngơi đủ',
    tooltip: {
      title: '😴 Mệt mỏi mãn tính',
      items: [
        '📋 Dấu hiệu:',
        '• Uể oải suốt ngày',
        '• Thiếu năng lượng',
        '• Khó tập trung',
        '• Ngủ đủ vẫn mệt',
        '',
        '⚠️ Do đâu?',
        'Tế bào không sử dụng được glucose',
        'Cơ thể thiếu năng lượng',
      ],
    },
  },
  {
    id: 'symptom_blurred_vision',
    text: 'Bạn có gặp vấn đề về thị lực (mờ, giảm) không?',
    type: 'select',
    placeholder: 'Chọn mức độ',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng mờ mắt' },
      { value: 2, label: 'Thường xuyên mờ' },
      { value: 3, label: 'Rất mờ, khó nhìn' },
    ],
    hint: 'Nhìn mờ, khó lấy nét',
    tooltip: {
      title: '👁️ Thị lực giảm',
      items: [
        '📋 Triệu chứng:',
        '• Nhìn mờ, không rõ',
        '• Khó đọc chữ',
        '• Thấy lờ mờ',
        '• Thay đổi thị lực thất thường',
        '',
        '⚠️ Nguyên nhân:',
        'Đường huyết cao làm phồng thủy tinh thể',
        '',
        '🏥 Lưu ý: Khám mắt nếu có triệu chứng',
      ],
    },
  },
  {
    id: 'symptom_weight_loss',
    text: 'Bạn có bị sụt cân không rõ nguyên nhân không?',
    type: 'select',
    placeholder: 'Chọn tình trạng',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Giảm nhẹ (<2kg)' },
      { value: 2, label: 'Giảm rõ rệt (2-5kg)' },
      { value: 3, label: 'Giảm nhiều (>5kg)' },
    ],
    hint: 'Giảm cân mặc dù ăn bình thường hoặc nhiều hơn',
    tooltip: {
      title: '⚖️ Sụt cân bất thường',
      items: [
        '📋 Dấu hiệu cảnh báo:',
        '• Giảm cân không cố ý',
        '• Ăn nhiều vẫn gầy',
        '• Giảm >5% trọng lượng trong 3-6 tháng',
        '',
        '⚠️ Tại sao?',
        'Cơ thể không hấp thu glucose',
        'Đốt cháy mỡ và protein để lấy năng lượng',
        '',
        '🚨 Cần khám ngay nếu giảm nhiều',
      ],
    },
  },
  {
    id: 'symptom_slow_healing',
    text: 'Vết thương của bạn có lâu lành không?',
    type: 'select',
    placeholder: 'Chọn tình trạng',
    options: [
      { value: 0, label: 'Lành bình thường' },
      { value: 1, label: 'Hơi chậm' },
      { value: 2, label: 'Rất chậm lành' },
      { value: 3, label: 'Rất khó lành, hay nhiễm trùng' },
    ],
    hint: 'Vết thương, vết xước lâu lành, dễ nhiễm trùng',
    tooltip: {
      title: '🩹 Vết thương lâu lành',
      items: [
        '📋 Biểu hiện:',
        '• Vết nhỏ cũng lâu lành',
        '• Vết thương dễ nhiễm trùng',
        '• Da khô, nứt nẻ',
        '• Bầm tím lâu khỏi',
        '',
        '⚠️ Nguyên nhân:',
        'Đường huyết cao làm:',
        '• Giảm lưu thông máu',
        '• Suy yếu hệ miễn dịch',
        '• Tổn thương mạch máu nhỏ',
      ],
    },
  },
  {
    id: 'symptom_numbness',
    text: 'Bạn có cảm giác tê, kim châm ở tay chân không?',
    type: 'select',
    placeholder: 'Chọn mức độ',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng' },
      { value: 2, label: 'Thường xuyên' },
      { value: 3, label: 'Liên tục, đau nhức' },
    ],
    hint: 'Tê bì, châm chích ở chi',
    tooltip: {
      title: '🦶 Tê bàn tay/chân',
      items: [
        '📋 Triệu chứng thần kinh:',
        '• Tê, mất cảm giác',
        '• Cảm giác kim châm',
        '• Đau rát, nóng bỏng',
        '• Yếu cơ',
        '',
        '⚠️ Nguyên nhân:',
        'Đường huyết cao tổn thương dây thần kinh',
        '',
        '📍 Vị trí thường gặp:',
        '• Bàn chân, ngón chân',
        '• Bàn tay, ngón tay',
      ],
    },
  },
  {
    id: 'symptom_skin_darkening',
    text: 'Da bạn có xuất hiện vùng sẫm màu/đen ở cổ, nách không?',
    type: 'select',
    placeholder: 'Chọn tình trạng',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Có, nhẹ' },
      { value: 2, label: 'Có, rõ rệt' },
      { value: 3, label: 'Có, lan rộng' },
    ],
    hint: 'Da sẫm màu vùng nếp gấp (Acanthosis nigricans)',
    tooltip: {
      title: '🏴 Da sẫm màu bất thường',
      items: [
        '📋 Acanthosis nigricans:',
        '• Vùng da sẫm màu, dày lên',
        '• Thường ở cổ, nách, bẹn',
        '• Bề mặt da nhung nhúc',
        '',
        '⚠️ Ý nghĩa:',
        'Dấu hiệu kháng insulin',
        'Tiền tiểu đường',
        '',
        '🏥 Nên khám nếu xuất hiện',
      ],
    },
  },
  {
    id: 'symptom_infections',
    text: 'Bạn có hay bị nhiễm trùng (nấm, viêm) không?',
    type: 'select',
    placeholder: 'Chọn tần suất',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng' },
      { value: 2, label: 'Hay bị (>3 lần/năm)' },
      { value: 3, label: 'Rất thường xuyên' },
    ],
    hint: 'Nhiễm nấm, nhiễm trùng da, tiết niệu tái đi tái lại',
    tooltip: {
      title: '🦠 Nhiễm trùng tái phát',
      items: [
        '📋 Các loại nhiễm trùng thường gặp:',
        '• Nhiễm nấm da',
        '• Viêm đường tiết niệu',
        '• Nhiễm trùng nướu răng',
        '• Nhiễm nấm âm đạo (nữ)',
        '',
        '⚠️ Tại sao dễ nhiễm trùng?',
        'Đường cao làm:',
        '• Suy giảm miễn dịch',
        '• Môi trường thuận lợi cho vi khuẩn',
      ],
    },
  },
  {
    id: 'symptom_gum_problems',
    text: 'Bạn có vấn đề về nướu răng (sưng, chảy máu) không?',
    type: 'select',
    placeholder: 'Chọn tình trạng',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng chảy máu' },
      { value: 2, label: 'Nướu sưng, đỏ' },
      { value: 3, label: 'Viêm nặng, răng lung lay' },
    ],
    hint: 'Nướu sưng, chảy máu, răng lung lay',
    tooltip: {
      title: '🦷 Vấn đề nướu răng',
      items: [
        '📋 Triệu chứng:',
        '• Nướu đỏ, sưng',
        '• Chảy máu khi đánh răng',
        '• Hơi thở hôi',
        '• Răng lung lay',
        '',
        '⚠️ Liên quan tiểu đường:',
        'Đường cao làm:',
        '• Tăng nguy cơ viêm nha chu',
        '• Giảm khả năng chữa lành',
        '',
        '🪥 Cần chăm sóc răng miệng tốt',
      ],
    },
  },
  {
    id: 'symptom_mood_changes',
    text: 'Bạn có thay đổi tâm trạng bất thường (cáu gắt, lo âu)?',
    type: 'select',
    placeholder: 'Chọn mức độ',
    options: [
      { value: 0, label: 'Không' },
      { value: 1, label: 'Thỉnh thoảng' },
      { value: 2, label: 'Thường xuyên' },
      { value: 3, label: 'Rất thường xuyên, trầm cảm' },
    ],
    hint: 'Dễ cáu gắt, căng thẳng, lo âu',
    tooltip: {
      title: '😟 Thay đổi tâm trạng',
      items: [
        '📋 Biểu hiện:',
        '• Dễ cáu gắt',
        '• Lo âu, căng thẳng',
        '• Khó tập trung',
        '• Thay đổi tâm trạng đột ngột',
        '',
        '⚠️ Nguyên nhân:',
        'Đường huyết không ổn định',
        'Ảnh hưởng hóa học não',
        '',
        '💡 Kiểm soát đường huyết giúp cải thiện',
      ],
    },
  },
];

export const articles = [
  {
    id: '1',
    title: 'Cách kiểm soát đường huyết hiệu quả mỗi ngày',
    excerpt: 'Tìm hiểu chế độ ăn uống và thói quen giúp bạn duy trì đường huyết ổn định.',
    category: 'nutrition',
    imageUrl: 'https://images.unsplash.com/photo-1670164745494-30747c120652?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwbnV0cml0aW9uJTIwZm9vZHxlbnwxfHx8fDE3NjEzNjYwOTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    readTime: '5 phút đọc',
    featured: true,
  },
  {
    id: '2',
    title: 'Tầm quan trọng của xét nghiệm HbA1c trong theo dõi tiểu đường',
    excerpt: 'HbA1c là chỉ số quan trọng giúp đánh giá mức đường huyết trung bình trong 3 tháng.',
    category: 'testing',
    imageUrl: 'https://images.unsplash.com/photo-1576169210859-6796c4b93c32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwdGVzdCUyMGRpYWJldGVzfGVufDF8fHx8MTc2MTM5MDc4Nnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    readTime: '4 phút đọc',
    featured: true,
  },
  {
    id: '3',
    title: 'Vận động thể dục: Vũ khí mạnh trong phòng ngừa tiểu đường',
    excerpt: '30 phút tập luyện mỗi ngày có thể giảm đáng kể nguy cơ mắc bệnh tiểu đường type 2.',
    category: 'lifestyle',
    imageUrl: 'https://images.unsplash.com/photo-1634144646738-809a0f8897c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxleGVyY2lzZSUyMGZpdG5lc3MlMjBoZWFsdGh8ZW58MXx8fHwxNzYxMzkwNzg2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    readTime: '6 phút đọc',
    featured: true,
  },
  {
    id: '4',
    title: 'Hiểu về Insulin và vai trò của nó trong cơ thể',
    excerpt: 'Insulin là hormone quan trọng giúp điều hòa lượng đường trong máu.',
    category: 'education',
    imageUrl: 'https://images.unsplash.com/photo-1606206873764-fd15e242df52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjEzODc4ODV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    readTime: '7 phút đọc',
  },
  {
    id: '5',
    title: 'Chế độ ăn Low-Carb: Có phù hợp với bệnh tiểu đường?',
    excerpt: 'Phân tích lợi ích và rủi ro của chế độ ăn giảm carbohydrate đối với người tiểu đường.',
    category: 'nutrition',
    imageUrl: 'https://images.unsplash.com/photo-1556911073-a517e752729c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwbGlmZXN0eWxlfGVufDF8fHx8MTc2MTI4Nzc5MXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    readTime: '5 phút đọc',
  },
  {
    id: '6',
    title: 'Stress và tiểu đường: Mối liên hệ bạn cần biết',
    excerpt: 'Căng thẳng kéo dài có thể ảnh hưởng trực tiếp đến mức đường huyết của bạn.',
    category: 'lifestyle',
    imageUrl: 'https://images.unsplash.com/photo-1758691462123-8a17ae95d203?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb2N0b3IlMjBwYXRpZW50JTIwbWVkaWNhbHxlbnwxfHx8fDE3NjEzOTA3ODV8MA&ixlibrb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    readTime: '4 phút đọc',
  },
];

export const categoryLabels = {
  nutrition: 'Dinh dưỡng',
  lifestyle: 'Lối sống',
  testing: 'Xét nghiệm',
  education: 'Giáo dục',
};
